{{- if and (not .Values.bearerToken.existingSecret) .Values.bearerToken.value }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "dotnet-diagnostics-orchestrator.secretName" . }}
  namespace: {{ include "dotnet-diagnostics-orchestrator.namespace" . }}
  labels:
    {{- include "dotnet-diagnostics-orchestrator.labels" . | nindent 4 }}
type: Opaque
stringData:
  token: {{ .Values.bearerToken.value | quote }}
{{- end }}
